version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
     - "80:80"  # Maps port 80 on the host to port 80 in the container
     - "443:443"
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf  # Maps local nginx.conf to container's config
     - ./certs:/etc/nginx/certs
